### ISSUE TITLE
Performing a search within a python script

### ISSUE THREAD

**Issue by oppositelocks** [kannibalox/PTPAPI#28]
How can I perform a search from within a python script?  I've been trying to sort this for a while and have gotten nowhere.  
Something like:

```
import ptpapi

ptp = ptpapi.login(api_user=xxxxxxxxxxxx, api_key=xxxxxxxxxxxxx)

ptp.search("Star Wars") #Obviously this portion does not work.

```

ptp.current_user() works fine though.

**Comment by kannibalox** [comment]
The search function is a pretty thin wrapper over index.php, so this should work:
`ptp.search({"searchstr": "Star Wars"})`

**Comment by oppositelocks** [comment]
Thank you!

**Comment by oppositelocks** [comment]
Thank you!
