### ISSUE TITLE
Bugs/Feature Requests

### ISSUE THREAD

**Issue by dirtycajunrice** [kannibalox/PTPAPI#4]
Feature requests:

- Allow .torrent downloads without adding to rtorrent
- Counter for when many movies are passed to it. maybe towards the beginning? INFO:(52 of 1024):

Bugs:
- requriements do not have pyrocore/pyrobase and they are required for -h currently
- dry run still tries to log into rtorrent
- xmlrpc for pyrocore allows defining a connection for scgi url but it cannot be defined in ptpapi forcing only the local connection to exist and where its defined in the rtorrent.rc

**Comment by kannibalox** [comment]
Which of these are for the project as a whole, and which are for `ptp-reseed`? I definitely wrote ptp-reseed with rtorrent/pyrocore in mind, but I didn't want to tie it too tightly to them and definitely didn't want the project as a whole to depend on them.

**Comment by xthursdayx** [comment]
I ran into this same issue when trying to run `ptp-reseed -h` and am also hoping to be able to download .torrent files without automatically adding them to rtorrent. Is there anything I need to do to be able to use ptp-reseed without rtorrent?

**Comment by einsern** [comment]
seems fixed by https://github.com/kannibalox/PTPAPI/commit/33851b476c1f52f0190b3934f597b50fb656f46f

**Comment by kannibalox** [comment]
The bugs should be fixed, however the feature requests have not been implemented. I may cheat and implement a fake `file://` client that will be intercepted before it reaches libtc.

**Comment by kannibalox** [comment]
The features/bugs should all be fixed:
- the fake `file://` client allows for ptp-reseed to download to a directory
- `--debug` should show the necessary info
- dependencies are up-to-date
- dry-run will need to connect to a client for some things, however you can always use the afore-mentioned `file://` client to work around it.
- The `PYRO_SCGI_URL` environment variable can be used for custom rtorrent connection strings if `--client` doesn't work.
