### ISSUE TITLE
Unicode not supported

### ISSUE THREAD

**Issue by scrimpys** [kannibalox/PTPAPI#7]
Noticed number of times python code complains when it encounters UTF-8 characters in the file names.

INFO:ptp-reseed:Starting reseed attempt on file /volume1/Movies/TZ/¡Vivan las Antipodas! (2011)
Traceback (most recent call last):
  File "/usr/local/bin/ptp-reseed", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ptpapi/scripts/ptp_reseed.py", line 302, in main
    if not os.path.exists(filename):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa1' in position 19: ordinal not in range(128)

**Comment by kannibalox** [comment]
This should be fixed in the latest develop branch, can you confirm?

**Comment by scrimpys** [comment]
Not sure I upgraded it properly .... did "pip install -U
https://github.com/kannibalox/PTPAPI/archive/master.zip" hoping it would
upgrade components.

Anyway if it did upgrade it then it is not fixed.


INFO:ptp-reseed:Starting reseed attempt on file
"/volume1/Movies/AE/8QK841~2"

INFO:ptpapi.scripts.ptp_reseed:Searching movies by file list

INFO:ptpapi.scripts.ptp_reseed:Guessing name from filepath with guessit

ERROR:ptp-reseed:Could not find an associated torrent for
'/volume1/Movies/AE/8QK841~2', cannot reseed

Traceback (most recent call last):

  File "/usr/local/bin/ptp-reseed", line 10, in <module>

    sys.exit(main())

  File
"/usr/local/lib/python2.7/dist-packages/ptpapi/scripts/ptp_reseed.py", line
301, in main

    logger.info(u'Starting reseed attempt on file "{0}"'.format(filename))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20:
ordinal not in range(128)

**Comment by kannibalox** [comment]
I can probably fix that bug, but I have strong doubts about this script being able to effectively match anything against samba-mangled filenames.

**Comment by kannibalox** [comment]
There shouldn't be any unicode errors anymore, feel free to re-open with examples if you're still encountering them.
