### ISSUE TITLE
os.environ["HOME"] is invalid in Windows

### ISSUE THREAD

**Issue by RJohnsonPGH** [kannibalox/PTPAPI#8]
config.py:9

"HOME" is an invalid key under Windows which instead uses "USERPROFILE"

You **could** check for OS and have an if to use a different string but:

`os.path.expanduser('~')`

Should just work in both Windows and *nix

**Comment by kannibalox** [comment]
That commit should have fixed this specific issue, but I didn't do any further testing on Windows. I tried to keep it OS neutral but only really use it on linux, so there may be other bugs.
